line-length = 120

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

[lint]
ignore = ["D203","D100","D101","D400","D401","D106", "F403","F405","D403","D104","B008", "B023", "B904"]
select = [
    'E',
    'B',
    'I',
    'F',
    'W',
    'A'
]

[lint.per-file-ignores]
"tests/*" = ["D102","D103"]
"examples.py" = ["ALL"]

[lint.pydocstyle]
convention = "google"

[format]
# Like Black, use double quotes for strings.
quote-style = "single"
line-ending = "auto"